services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./server/data:/app/data
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '5173:80'
    depends_on:
      - server
    env_file:
      - ./client/.env
    restart: unless-stopped

networks:
  default:
    name: snippet-bin-network
